import { deferEffectCallback } from '../../../shared/utils/deferEffectCallback.js';
import { useEffect, useState } from "react";
import { downloadCarePlanPdf } from "../services/carePlanPdfService";
import { getUser } from "../../auth";

const LOADING_MESSAGES = [
  "Retrieving your health records…",
  "Analysing your medical history…",
  "Cross-referencing clinical guidelines…",
  "Generating your personalised care plan…",
];

export default function CarePlanModal({
  isOpen,
  loading,
  error,
  result,
  onClose,
  onRegenerate,
  patientName,
}) {
  const [loadingMessageIndex, setLoadingMessageIndex] = useState(0);
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);
  const [downloadError, setDownloadError] = useState(null);

  const handleDownloadPdf = () => {
    if (!result?.care_plan) return;
    try {
      setIsDownloading(true);
      setDownloadError(null);
      const user = getUser();
      downloadCarePlanPdf(result, {
        ...user,
        name: patientName || user?.name || user?.profileDetails?.fullName,
      });
      setDownloadSuccess(true);
      setTimeout(() => setDownloadSuccess(false), 4000);
    } catch (err) {
      console.error("Failed to generate Care Plan PDF:", err);
      setDownloadError("Could not generate PDF document. Please try again.");
    } finally {
      setIsDownloading(false);
    }
  };

  useEffect(() => deferEffectCallback(() => {
    if (!loading) {
      setLoadingMessageIndex(0);
      return;
    }
    const interval = setInterval(() => {
      setLoadingMessageIndex((i) => (i + 1) % LOADING_MESSAGES.length);
    }, 4000);
    return () => clearInterval(interval);
  }), [loading]);

  if (!isOpen) return null;

  const plan = result?.care_plan;
  const summary = result?.patient_summary;

  const priorityColor = (p) => {
    const s = (p || "").toLowerCase();
    if (s === "high") return { bg: "var(--color-error-bg)", fg: "var(--color-error)" };
    if (s === "medium") return { bg: "var(--color-warning-bg)", fg: "var(--color-warning)" };
    return { bg: "var(--color-info-bg)", fg: "var(--color-info)" };
  };

  const severityColor = (sev) => {
    const s = (sev || "").toLowerCase();
    if (s === "critical")
      return { bg: "var(--color-error-bg)", fg: "var(--color-error)", border: "var(--color-error)" };
    if (s === "warning")
      return { bg: "var(--color-warning-bg)", fg: "var(--color-warning)", border: "var(--color-warning-border)" };
    return { bg: "var(--color-info-bg)", fg: "var(--color-primary)", border: "var(--color-info)" };
  };

  return (
    <div className="modal-overlay" onClick={loading ? undefined : onClose}>
      <div
        className="modal-content-card"
        style={{
          maxWidth: "860px",
          width: "92vw",
          maxHeight: "88vh",
          overflowY: "auto",
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="modal-header-row">
          <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
            <span style={{ fontSize: "1.6rem" }}>🩺</span>
            <div>
              <h3
                style={{
                  fontSize: "1.25rem",
                  fontWeight: 800,
                  color: "var(--color-text-title)",
                  margin: 0,
                }}
              >
                AI Care Plan
              </h3>
              <p style={{ fontSize: "0.82rem", color: "var(--color-text-muted)", margin: 0 }}>
                Generated by PatientDataAgent + CarePlanningAgent
              </p>
            </div>
          </div>
          <button
            type="button"
            className="modal-close-btn"
            onClick={onClose}
            disabled={loading}
            aria-label="Close"
          >
            ✕
          </button>
        </div>

        {/* Loading state */}
        {loading && (
          <div style={{ padding: "50px 24px", textAlign: "center" }}>
            <div
              style={{
                width: "56px",
                height: "56px",
                border: "4px solid var(--color-border-light)",
                borderTop: "4px solid var(--color-primary-hover)",
                borderRadius: "50%",
                margin: "0 auto 20px",
                animation: "spin 1s linear infinite",
              }}
            />
            <p
              style={{
                fontSize: "1.05rem",
                fontWeight: 700,
                color: "var(--color-text-title)",
                margin: "0 0 8px",
              }}
            >
              {LOADING_MESSAGES[loadingMessageIndex]}
            </p>
            <p style={{ fontSize: "0.85rem", color: "var(--color-text-muted)", margin: 0 }}>
              This usually takes 30–90 seconds. Please keep this window open.
            </p>
            <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
          </div>
        )}

        {/* Error state */}
        {!loading && error && (
          <div
            style={{
              margin: "24px 0",
              padding: "18px 20px",
              background: "var(--color-error-bg)",
              border: "1.5px solid var(--color-error-border)",
              borderRadius: "12px",
              color: "var(--color-error)",
              fontSize: "0.95rem",
            }}
          >
            <strong>⚠ Could not generate care plan.</strong>
            <p style={{ margin: "6px 0 0" }}>{error}</p>
          </div>
        )}

        {/* Success state */}
        {!loading && !error && plan && (
          <div
            style={{ display: "flex", flexDirection: "column", gap: "22px" }}
          >
            {/* Patient + summary */}
            <div
              style={{
                padding: "16px 18px",
                background: "var(--color-info-bg)",
                border: "1px solid var(--color-info-border)",
                borderRadius: "12px",
              }}
            >
              <div
                style={{
                  fontSize: "0.78rem",
                  fontWeight: 700,
                  color: "var(--color-accent)",
                  letterSpacing: "1px",
                  marginBottom: "4px",
                }}
              >
                PATIENT
              </div>
              <div
                style={{
                  fontSize: "1.05rem",
                  fontWeight: 800,
                  color: "var(--color-text-title)",
                  marginBottom: "8px",
                }}
              >
                {summary?.demographics?.name || "—"}
                {summary?.demographics?.age_years != null && (
                  <span style={{ fontWeight: 500, color: "var(--color-text-body)" }}>
                    {" "}
                    · {summary.demographics.age_years} years
                  </span>
                )}
              </div>
              <p
                style={{
                  margin: 0,
                  fontSize: "0.92rem",
                  color: "var(--color-text-body)",
                  lineHeight: 1.55,
                }}
              >
                {plan.summary_text}
              </p>
            </div>

            {/* Warnings first (most important) */}
            {Array.isArray(plan.warnings) && plan.warnings.length > 0 && (
              <section>
                <h4 style={sectionHeadingStyle}>Warnings</h4>
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    gap: "8px",
                  }}
                >
                  {plan.warnings.map((w, i) => {
                    const c = severityColor(w.severity);
                    return (
                      <div
                        key={i}
                        style={{
                          padding: "10px 14px",
                          background: c.bg,
                          color: c.fg,
                          borderLeft: `4px solid ${c.border}`,
                          borderRadius: "6px",
                          fontSize: "0.9rem",
                        }}
                      >
                        <strong style={{ marginRight: "6px" }}>
                          {w.severity}
                        </strong>
                        {w.message}
                      </div>
                    );
                  })}
                </div>
              </section>
            )}

            {/* Immediate actions */}
            {Array.isArray(plan.immediate_actions) &&
              plan.immediate_actions.length > 0 && (
                <section>
                  <h4 style={sectionHeadingStyle}>Immediate Actions</h4>
                  <div
                    style={{
                      display: "flex",
                      flexDirection: "column",
                      gap: "8px",
                    }}
                  >
                    {plan.immediate_actions.map((a, i) => {
                      const c = priorityColor(a.priority);
                      return (
                        <div
                          key={i}
                          style={{
                            padding: "12px 14px",
                            background: "var(--color-bg)",
                            border: "1px solid var(--color-border-light)",
                            borderRadius: "8px",
                          }}
                        >
                          <div
                            style={{
                              display: "flex",
                              alignItems: "center",
                              gap: "8px",
                              marginBottom: "4px",
                            }}
                          >
                            <span
                              style={{
                                padding: "2px 8px",
                                background: c.bg,
                                color: c.fg,
                                borderRadius: "10px",
                                fontSize: "0.7rem",
                                fontWeight: 700,
                              }}
                            >
                              {a.priority}
                            </span>
                            <strong
                              style={{ color: "var(--color-text-title)", fontSize: "0.95rem" }}
                            >
                              {a.action}
                            </strong>
                          </div>
                          <p
                            style={{
                              margin: 0,
                              fontSize: "0.85rem",
                              color: "var(--color-text-body)",
                            }}
                          >
                            {a.reason}
                          </p>
                        </div>
                      );
                    })}
                  </div>
                </section>
              )}

            {/* Upcoming vaccines */}
            {Array.isArray(plan.upcoming_vaccines) &&
              plan.upcoming_vaccines.length > 0 && (
                <section>
                  <h4 style={sectionHeadingStyle}>Upcoming Vaccines</h4>
                  <div
                    style={{
                      display: "flex",
                      flexDirection: "column",
                      gap: "6px",
                    }}
                  >
                    {plan.upcoming_vaccines.map((v, i) => (
                      <div
                        key={i}
                        style={{
                          display: "flex",
                          justifyContent: "space-between",
                          padding: "10px 14px",
                          background: "var(--color-info-bg)",
                          border: "1px solid var(--color-info-border)",
                          borderRadius: "8px",
                        }}
                      >
                        <div>
                          <strong
                            style={{ color: "var(--color-info)", fontSize: "0.95rem" }}
                          >
                            {v.vaccine}
                          </strong>
                          <div
                            style={{ fontSize: "0.82rem", color: "var(--color-text-body)" }}
                          >
                            {v.reason}
                          </div>
                        </div>
                        {v.due_within_days != null && (
                          <span
                            style={{
                              fontSize: "0.8rem",
                              color: "var(--color-primary)",
                              fontWeight: 600,
                              alignSelf: "center",
                            }}
                          >
                            Due in {v.due_within_days}d
                          </span>
                        )}
                      </div>
                    ))}
                  </div>
                </section>
              )}

            {/* Screenings + lifestyle side-by-side on wide screens */}
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "1fr 1fr",
                gap: "16px",
              }}
            >
              {Array.isArray(plan.recommended_screenings) &&
                plan.recommended_screenings.length > 0 && (
                  <section>
                    <h4 style={sectionHeadingStyle}>Recommended Screenings</h4>
                    <ul style={listStyle}>
                      {plan.recommended_screenings.map((s, i) => (
                        <li key={i}>{s}</li>
                      ))}
                    </ul>
                  </section>
                )}

              {Array.isArray(plan.lifestyle_recommendations) &&
                plan.lifestyle_recommendations.length > 0 && (
                  <section>
                    <h4 style={sectionHeadingStyle}>Lifestyle</h4>
                    <ul style={listStyle}>
                      {plan.lifestyle_recommendations.map((s, i) => (
                        <li key={i}>{s}</li>
                      ))}
                    </ul>
                  </section>
                )}
            </div>

            {/* Referrals */}
            {Array.isArray(plan.referrals) && plan.referrals.length > 0 && (
              <section>
                <h4 style={sectionHeadingStyle}>Referrals</h4>
                <ul style={listStyle}>
                  {plan.referrals.map((r, i) => (
                    <li key={i}>{r}</li>
                  ))}
                </ul>
              </section>
            )}

            {/* Follow-up */}
            {plan.follow_up_recommendation && (
              <div
                style={{
                  padding: "14px 18px",
                  background: "var(--color-success-bg)",
                  border: "1px solid var(--color-success-border)",
                  borderRadius: "10px",
                }}
              >
                <div
                  style={{
                    fontSize: "0.72rem",
                    fontWeight: 700,
                    color: "var(--color-success)",
                    letterSpacing: "1px",
                    marginBottom: "4px",
                  }}
                >
                  FOLLOW-UP RECOMMENDATION
                </div>
                <p
                  style={{
                    margin: 0,
                    fontSize: "0.92rem",
                    color: "var(--color-success)",
                    lineHeight: 1.55,
                  }}
                >
                  {plan.follow_up_recommendation}
                </p>
              </div>
            )}

            {/* Trajectory footer — good for evidence */}
            {Array.isArray(result?.steps) && result.steps.length > 0 && (
              <div
                style={{
                  marginTop: "8px",
                  paddingTop: "14px",
                  borderTop: "1px solid var(--color-border-light)",
                  fontSize: "0.78rem",
                  color: "var(--color-text-muted)",
                }}
              >
                <div
                  style={{
                    fontWeight: 700,
                    marginBottom: "6px",
                    color: "var(--color-text-body)",
                  }}
                >
                  Agent trajectory
                </div>
                {result.steps.map((s, i) => (
                  <div key={i} style={{ marginBottom: "2px" }}>
                    ✓ <strong>{s.agent}</strong> — {s.duration_ms}ms
                    {Array.isArray(s.tools_used) && s.tools_used.length > 0 && (
                      <span>
                        {" "}
                        · {s.tools_used.length} tool
                        {s.tools_used.length > 1 ? "s" : ""}:{" "}
                        {s.tools_used.join(", ")}
                      </span>
                    )}
                  </div>
                ))}
                <div style={{ marginTop: "6px", color: "var(--color-text-placeholder)" }}>
                  Total: {result.duration_ms}ms
                </div>
              </div>
            )}

            {/* Download Care Plan Banner at the bottom of the plan */}
            <div className="careplan-download-box">
              <div className="careplan-download-info">
                <div className="careplan-download-icon">
                  📄
                </div>
                <div>
                  <h4 className="careplan-download-title">
                    Export Official Care Plan (PDF)
                  </h4>
                  <p className="careplan-download-sub">
                    Download a verified clinical PDF report for your health records or doctor consultation.
                  </p>
                </div>
              </div>
              <button
                type="button"
                className="btn-careplan-download"
                onClick={handleDownloadPdf}
                disabled={isDownloading}
              >
                {isDownloading ? (
                  <>
                    <span className="careplan-btn-spinner" />
                    <span>Preparing PDF…</span>
                  </>
                ) : downloadSuccess ? (
                  <>
                    <span>✓</span>
                    <span>PDF Downloaded</span>
                  </>
                ) : (
                  <>
                    <span>📥</span>
                    <span>Download Care Plan (PDF)</span>
                  </>
                )}
              </button>
            </div>

            {downloadError && (
              <div
                style={{
                  padding: "10px 14px",
                  background: "var(--color-error-bg)",
                  border: "1px solid var(--color-error-border)",
                  borderRadius: "8px",
                  color: "var(--color-error)",
                  fontSize: "0.85rem",
                }}
              >
                ⚠ {downloadError}
              </div>
            )}
          </div>
        )}

        {/* Footer */}
        {!loading && (
          <div
            style={{
              display: "flex",
              justifyContent: plan ? "space-between" : "flex-end",
              alignItems: "center",
              gap: "10px",
              marginTop: "24px",
              paddingTop: "16px",
              borderTop: "1px solid var(--color-border-light)",
              flexWrap: "wrap",
            }}
          >
            <div>
              {plan && onRegenerate && (
                <button
                  type="button"
                  className="btn-modal-cancel"
                  style={{ fontSize: "0.85rem", padding: "8px 14px" }}
                  onClick={onRegenerate}
                >
                  🔄 Regenerate Plan
                </button>
              )}
            </div>

            <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
              {plan && (
                <button
                  type="button"
                  className="btn-careplan-download"
                  style={{ padding: "8px 18px", fontSize: "0.88rem" }}
                  onClick={handleDownloadPdf}
                  disabled={isDownloading}
                >
                  {isDownloading ? (
                    <>
                      <span className="careplan-btn-spinner" />
                      <span>Generating…</span>
                    </>
                  ) : downloadSuccess ? (
                    <>
                      <span>✓ Downloaded</span>
                    </>
                  ) : (
                    <>
                      <span>📥</span>
                      <span>Download PDF</span>
                    </>
                  )}
                </button>
              )}
              <button
                type="button"
                className="btn-modal-cancel"
                onClick={onClose}
              >
                Close
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

const sectionHeadingStyle = {
  fontSize: "0.82rem",
  fontWeight: 800,
  color: "var(--color-text-title)",
  letterSpacing: "0.5px",
  textTransform: "uppercase",
  margin: "0 0 8px",
};

const listStyle = {
  margin: 0,
  paddingLeft: "20px",
  fontSize: "0.88rem",
  color: "var(--color-text-body)",
  lineHeight: 1.6,
};
